version: '5'
services:
  api:
    container_name: api-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es1c/api:latest
    profiles: ["dev", "prod"]
    build: ./api
    depends_on:
      - gateway
    ports:
      - "23123:23123"
    networks:
      - mynetwork

  mariadb:
    container_name: mariadb-${teamname:-defaultASW}
    image: mariadb
    profiles: ["dev", "prod"]
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 # This should be done in a real production server, im aware.
      - MARIADB_DATABASE=db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 15s
      retries: 5
    networks:
      - mynetwork

  gateway:
    container_name: gateway-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es1c/gateway:latest
    profiles: ["dev", "prod"]
    build: ./gateway
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - mynetwork

  webapp:
    container_name: webapp-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es1c/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    depends_on:
      - gateway
    ports:
      - "3000:3000" 

# prometheus:
#   image: prom/prometheus
#   container_name: prometheus-${teamname:-defaultASW}
#   profiles: ["dev"]
#   networks:
#     - mynetwork
#   volumes:
#     - ./gatewayservice/monitoring/prometheus:/etc/prometheus
#     - prometheus_data:/prometheus
#   ports:
#     - "9090:9090"
#   depends_on: 
#     - gatewayservice
      
# grafana:
#   image: grafana/grafana
#   container_name: grafana-${teamname:-defaultASW}
#   profiles: ["dev"]
#   networks:
#     - mynetwork
#   volumes:
#     - grafana_data:/var/lib/grafana
#     - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
#   environment:
#     - GF_SERVER_HTTP_PORT=9091
#     - GF_AUTH_DISABLE_LOGIN_FORM=true
#     - GF_AUTH_ANONYMOUS_ENABLED=true
#     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#   ports:
#     - "9091:9091"
#   depends_on: 
#     - prometheus


volumes:
  mariadb_data:
# prometheus_data: 
# grafana_data: 

networks:
  mynetwork:
    driver: bridge
