version: '5'
services:
  question:
    container_name: question-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es1c/question:latest
    profiles: ["dev", "prod"]
    build: ./question_service
    environment:
      - DB_URL=set
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8002:8002"
    networks:
      - mynetwork

  game:
    container_name: game-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es1c/game:latest
    profiles: ["dev", "prod"]
    build: ./game_service
    environment:
      - DB_URL=set
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8003:8003"
    networks:
      - mynetwork

  auth:
    container_name: auth-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es1c/auth:latest
    profiles: ["dev", "prod"]
    build: ./auth_service
    environment:
      - DB_URL=set
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - mynetwork

  userdetails:
    container_name: userdetails-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es1c/userdetails:latest
    profiles: [ "dev", "prod" ]
    build: ./userdetails_service
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8004:8004"
    networks:
      - mynetwork

  mariadb:
    container_name: mariadb-${teamname:-defaultASW}
    image: mariadb
    profiles: ["dev", "prod"]
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 # This should be done in a real production server, im aware.
      - MARIADB_DATABASE=db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 2s
      timeout: 3s
      retries: 10
    networks:
      - mynetwork

  mongodb:
    container_name: mongodb-${teamname:-defaultASW}
    image: mongo
    restart: always
    profiles: [ "dev", "prod" ]
    ports:
      - 27017:27017
    networks:
      - mynetwork

  webapp:
    container_name: webapp-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es1c/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    depends_on:
      - question
      - auth
    ports:
      - "80:3000" 

  prometheus:
    image: prom/prometheus
    container_name: prometheus-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - question
      - game
      - auth
      - userdetails
      
  grafana:
    image: grafana/grafana
    container_name: grafana-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus


volumes:
  mariadb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
