ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****

[plantuml,"businesscontext",png]
----
component "WIQ" as wiq #LightGray
component "Wikidata API" as data #Cyan
[wiq] --> [data]: Uses
[data] --> [wiq]: Generates questions
:User: --> [wiq]: Answers
wiq --> User: Asks questions


legend
 |<back:#LightGray>   </back>| Internal source |
 |<back:#Cyan>   </back>| External source |
 endlegend
----

|===
| Element | Description  
| User | Plays the game through his device
| WIQ | The application that runs the game
| Wikidata API | WIQ takes information from Wikidata in order to form the questions and its answers.
|===


=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

[plantuml, "technicalcontext", png]
----
node "Azure cloud" {
  node "WIQ" {
[Webapp]
}
}

node "WIQ user device" {
[User-agent]
}

[User-agent] --> Webapp: HTTPS

database "MariaDB"

WIQ --> [Wikidata]: REST
WIQ --> MariaDB: Uses

----

|===
| Element | Description
| Azure Cloud | Virtual Machine deployed in Azure that runs the application
| WIQ | Our application
| Webapp | The part of the application that the user accesses
| WIQ user device | The device used by the user to access the app via user-agent
| User-agent | Browser, Chrome for example
| MariaDB | Database that contains all the data needed for the application to run, such as scores or users registered
| Wikidata | The application uses its API REST to form questions
|===
