ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****

.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.





.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****

The following technologies have been used to develop this project:
* *JavaScript*: JavaScript is a high-level, interpreted programming language primarily used for building dynamic and interactive web applications. 
* *React*: React is a JavaScript framework for building user interfaces for web applications. We decided work with it for various reasons that make development easier, such as reusable components and it allows for developers to see the changes made instantly. 
* *MariaDB*: MariaDB is an open-source relational database managemente system. We are familiar with it, since it is very similar to other RDMS that we have already used before, MySQL for example. It offers an API to manage the database without having to deal directly with SQL code. 
* *Docker*: 
* *Github*:
* *JavaScript*:
