ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


=== Technologies used

The following technologies have been used to develop this project:

* **JavaScript** is a high-level, interpreted programming language primarily used for building dynamic and interactive web applications. 

* **React** is a JavaScript framework for building user interfaces for web applications. 

* **MariaDB** is an open-source relational database managemente system. It offers features such as ACID compliance and compatibility with MySQL.

* **MongoDB** is an open-source NoSQL database management system. It offers features such as high availability, horizontal scalability, and schema flexibility thanks to its document-based data model in JSON format.

* **Docker** is a platform and tool that allows developers to build, package, distribute, and run applications within lightweight, portable containers that encapsulate everything needed to run an application. 

* **Tailwind CSS** is a highly customizable CSS framework that provides a set of low-level utility classes that can be directly applied to HTML elements to style them. 

* **Material UI** is a library that implements the Material Design from Google. 

* **Testing react library** is a library for testing React components.

* **React-router-dom** offers easy configuration for application routes on the client side. It is only needed to establish the route and its associated component. 

==== Why we have chosen this technologies

* We went with JavaScript as our programming language because it is very widespread, which makes it very easy to search information about it. Also, we have already worked with it in the past, so we have some base knowledge about it.

* React is a very popular framework at the moment, you can find information about it everywhere. React makes building web user interfaces much easier, using reusable components and refreshing instantly when changes are made.

* We chose MariaDB as our RDMS for its similarity with MySQL, a language that is familiar to everyone on the team. MariaDB offers an API that allows tables to be made and managed without having to deal with sql files, simplifying the process.

* Docker is a very popular tool for containerization, which allows us to have a consistent environment for the project. It provides standarized versions without having to install programs and automatic deployment.

* Tailwind makes the process of giving style to the application much more flexible, making it simpler and quicker. 

* Material UI allows us to save time when designing the inferfaces that the user will be using.

* In order to encourage better test practises, we included Testing react library.

* **React-router-dom** as mentioned before, makes the process of building routes much easier. Also, when the user changes route, the virtual dom itself renders the new component.

=== Project structuring

The application is organised into microservices, making the different components that form the project more isolated and easier to maintain, having modules that have less coupling between them, making them more independent.

=== Decissions made to achieve quality goals 

* **Usability**: To improve usability, we decided to test de app and with the results of these we modified the color palette and the arrangement of some elements according to the experience of the users of the tests.

* **Performance efficiency**: To improve performance we decided to implement a cache that stores 1000 questions and every 24 h updates the 100 oldest. By this way we always have questions available and it is not necessary to wait for wikidata to give us an answer.

* **Maintainability**: For maintenance we report bugs that we find in the form of issues in the repository, so when some of us have time is dedicated it to fix them.

=== Work methodology decissions

* This project will be developed entirely in English, as it is the most common language in programming and we are more used to using it on a daily basis while doing other projects.

* We use a Kanban project in Github to quickly see the current state of the project and see what everyone is working on and what there is to do.

* Communication between team members is mostly made through Github, using issues to create and assign tasks, Whatsapp, to ask the rest of the team for help if needed for quick advice, and meetings.

* The work methodology is based on the Agile methodology, specifically we will use SCRUM, which will allow us to divide the work equitably and have constant development. In addition, we have used it previously and we are accustomed to its use.
