ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****

.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****

=== Technologies used

The following technologies have been used to develop this project:

* **JavaScript**: JavaScript is a high-level, interpreted programming language primarily used for building dynamic and interactive web applications. 

* **React**: React is a JavaScript framework for building user interfaces for web applications. 

* **MariaDB**: MariaDB is an open-source relational database managemente system. It offers features such as ACID compliance and compatibility with MySQL.

* **Docker**: Docker is a platform and tool that allows developers to build, package, distribute, and run applications within lightweight, portable containers that encapsulate everything needed to run an application. 

* **Tailwind CSS**: Tailwind CSS is a highly customizable CSS framework that provides a set of low-level utility classes that can be directly applied to HTML elements to style them. 

==== Why we have chosen this technologies

* We went with JavaScript as our programming language because it is very widespread, which makes it very easy to search information about it. Also, we have already worked with it in the past, so we have some base knowledge about it.

* React is a very popular framework at the moment, you can find information about it everywhere. React makes building web user interfaces much easier, using reusable components and refreshing instantly when changes are made.

* We chose MariaDB as our RDMS for its similarity with MySQL, a language that is familiar to everyone on the team. MariaDB offers an API that allows tables to be made and managed without having to deal with sql files, simplifying the process.

* Docker is a very popular tool for containerization, which allows us to have a consistent environment for the project. It provides standarized versions without having to install programs and automatic deployment.

* Tailwind makes the process of giving style to the application much more flexible, making it simpler and quicker. 

=== Microservice structuring

The application is organised into microservices, making the different components that form the project more isolated and easier to maintain, having modules that have less coupling between them, making them more independent.

=== Quality goals achieving

Pending.