[[section-building-block-view]]
== Building block view
=== Level 1: Whitebox of the Overall System
[plantuml,"Whitebox",png]
----
actor a as "Alice"
Component w as "WIQ" #LightGray
Component q as "WikiData" #2aa198

a -> w: Uses
q -left-> w: provides trivia data

legend
 |<back:#LightGray>   </back>| Internal source |
 |<back:#2aa198>   </back>| External source |
endlegend
----
Motivation::
_WIQ_ application has the basic structure to generate questions from WikiData and ask them to the user.
Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description

|*User* 
|User of the application which will interact with it.

|*WIQ* 
|The system to be implemented, it will take the necessary information from WikiData to generate questions.  

|*WikiData*
|Has the necessary information to generate generic trivia questions for the users.
|===
=== Level 2
[plantuml,"BlackBox Level 2",png]
----
Actor a as "Alice"

Component WIQ {
    Component ui as "User Interface"
    Component ms as "MicroServices"
}

Component w as "WikiData" #2aa198

a -> ui: Interacts with the UI
ui -> ms: Uses REST API

ms <- w: Provide trivia data

legend
 |<back:#2aa198>   </back>| External source |
endlegend
----
Motivation::
This shows the main data flow of the application (Towards the MicroServices) and also the architectural decision to use microservices to which the UI will hook up to.

Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description

|*User Interface* 
|Provies an interface that the end user of the application can use.

|*MicroServices* 
|They provide a backend for the UI, while keeping the app modular and easy to distribute and update.  

|===
=== Level 3
[plantuml,"BlackBox Level 3",png]
----
Component WIQ as "WIQ" {

    Component ms as "Micro services" {
        Component c1 as "Auth MicroService" {
            Component auth as "Auth Service" #6c71c4 
            Database d1 as "Login Data" #859900
        }

        Component c2 as "UserData MicroService" {
            Component history as "UserData Service" #6c71c4
        }

        Component c3 as "Game MicroService" {
            Component game as "Game Service" #6c71c4
            Database d2 as "Game data" #859900
            Database d5 as "Question cache" #b58900 
        }

        Component c4 as "Question MicroService" {
            Component questions as "Question Service" #6c71c4
            Database d6 as "Template storage" #b58900
        }
    }

    Component ui as "User Interface" #d33682

    ui -down-> auth
    ui -down-> game
    ui -down-> history

    auth -[dotted]-> d1
    auth <-[dotted]- d1
    game -[dotted]-> d2
    game <-[dotted]- d2
    game -[dotted]-> d5
    game <-[dotted]- d5
    questions -[dotted]-> d6
    questions <-[dotted]- d6
}

Component w as "Wikidata" #2aa198

game <-- questions: generates questions
questions <-left- w: provides trivia data

game <-right- history: Queries game history
auth <-left- history: Queries login data (username)

legend
 |<back:#d33682>   </back>| Client-side |
 |<back:#6c71c4>   </back>| Server-side |
 |<back:#2aa198>   </back>| External source |
 |<back:#859900>   </back>| Relational Database (MariaDB) |
 |<back:#b58900>   </back>| Non-Relational Database (MongoDB)|
endlegend
----

Motivation::
In this diagram we can see the decided microservices which will provide all the necessary operations for the application to work as intendeed. This is for now a WIP diagram which will evolve as the project progresses.

Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description

|*Game Service* 
|It is the microservice that will deal with game creation maintance and ending, it will record all games and the score of the user.

|*UserData Service*
|Its a microservice that provides to the UI all the necessary data to show the user statistics such as average score and game history. 

|*Auth Service* 
|Its a microservice that users can use to log onto the application, this works via Token authentication so that it works between microservices.

|*Question service* 
|Its main purpose is to be an abstraction over the WikiData API so the other microservices can directly ask him for questions instead of having to deal with the WikiData API

|*Game data and Login data* 
|They are the main databases of the aplication and together will store all the important persistant data of the aplication (Hence why MariaDB was choosen to maximise data consistency).

|*Template storage and Question cache* 
|They are secondary storages of the application whoose deletion is not critical to the application, template storage stores the templates that are used to generate the questions and question cache stores a temporary amount of questions to reduce latency. MongoDB was choosen due to its performance.
|===
