[[section-building-block-view]]
== Building block view
=== Level 1: Whitebox of the Overall System
[plantuml,"Whitebox",png]
----
actor a as "Alice"
Component w as "WIQ"
Component q as "WikiData"

a -> w: Uses 
w -> q: Gets data from
----
Motivation::
_WIQ_ application has the basic structure to generate questions from WikiData and ask them to the user.
Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description

|*User* 
|User of the application which will interact with it.

|*WIQ* 
|The system to be implemented, it will take the necessary information from WikiData to generate questions.  

|*WikiData*
|Has the necessary information to generate generic trivia questions for the users.
|===
=== Level 2
[plantuml,"BlackBox Level 2",png]
----
Actor a as "Alice"

Component WIQ {
    Component ui as "User Interface"
    Component ms as "MicroServices"
    Database d as "MariaDB"
}

Component w as "WikiData"

a -> ui: Interacts with the UI
ui -> ms: Sends user requests
ms <--> d: Reads user and question data

ms <- w: Provide trivia data
----
Motivation::
This shows the main data flow of the application (Towards the MicroServices) and also the architectural decision to use microservices to wich the UI will hook up to

Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description

|*User Interface* 
|Provies an interface that the end user of the application can use.

|*MicroServices* 
|They provide a backend for the UI, while keeping the app modular and easy to distribute and update.  

|*MariaDB*
|It is the choosen database, and stores the necessary data for all the microservices to work properly and to allow them to communicate and sync with eachother
|===
=== Level 3
[plantuml,"BlackBox Level 3",png]
----
Component ms as "Micro services" {
    Component auth as "Auth Service"
    Component questions as "Question Service"
    Component game as "Game Service"
    Component friends as "Friends Service"
    Component history as "UserData Service"
}

Component ui as "User Interface"
Database d as "MariaDB"
Component w as "Wikidata"

ui -down-> auth
ui -down-> game
ui -down-> history
ui -down-> friends

game -down-> questions: generates question
questions <-down- w: provides trivia data

auth <-down-> d
game <-down-> d
friends <-down-> d
history <-down-> d
----

Motivation::
In this diagram we can see the decided microservices which will provide all the necessary operations for the application to work as intendeed. This is for now a WIP diagram which will evolve as the project progresses.

Contained Building Blocks::
[options="header",cols="1,3"]
|===
|Name| Description

|*Game Service* 
|It is the microservice that will deal with game creation maintance and ending, it will record all games and the score of the user.

|*Friends service* 
|It is the microservice that will deal with the friends list of each user and the usual friendship operations such as Adding a friend or removing a friend 

|*UserData Service*
|Its a microservice that provides to the UI all the necessary data to show the user statistics such as average score and game history. 

|*Auth Service* 
|Its a microservice that users can use to log onto the application, this works via Token authentication so that it works between microservices.

|*Question service* 
|Its main purpose is to be an abstraction over the WikiData API so the other microservices can directly ask him for questions instead of having to deal with the WikiData API
|===
