ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****

=== User plays a questions game
When the users starts a game, it does so via the game service (which internally will use the questiosn service). The game service will provide questions until the end of the game.
[plantuml,"Start a game",png]
----
actor a as "Alice"
participant q as "game service"
participant w as "questions service"
database d as "Database"


a -> q: Requests to begin a game
loop numero de preguntas del juego
q -> w: Requests question
w -->q
q -> d: Registers the question
d -->q
q -> a: Returns the question 
|||
...Alice takes some time to awnser the question......
|||
a -> q: Sends the awnser
q -> d: Registers awnser
d -->q
q -> a: Confirms if the awnser was valid or not
a -> q: Asks for next question
end
q -> a: Tells the user the game has ended, along with the stats
----

=== A new question is generated
Other services can ask the questions service to generate a question, this serves as an abastraction over the WikiData API as we are only insterested in the questions and not the raw data.
[plantuml,"Generate a question",png]
----
participant a as "other participants"
participant q as "questions service"
database w as "Wikidata"

a -> q: Requests a new question
q -> w: Requests data to generate a question
w -->q
q -> q: Generates the question
q -> a: Returns the question 
----

=== User looks at his history
The user can look at his history via the User data microservice which provices acces to all of the data of the user
[plantuml,"Look at history",png]
----
actor a as "Alice"
participant q as "user data service"
database d as "Database"


a -> q: Requests to see the history
q -> d: Requests the history of the player
d -->q
q -> a: Returns the history 
----