ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document a deployment view if your software is executed as distributed system with more than one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture only those elements of an infrastructure that are needed to show a deployment of your building blocks. Hardware architects can go beyond that and describe an infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence a system and/or some
cross-cutting concepts. Therefore, there is a need to know the infrastructure.

.Form

Maybe a highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section one can
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than a deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.


.Further Information

See https://docs.arc42.org/section-7/[Deployment View] in the arc42 documentation.

****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

* distribution of a system to multiple locations, environments, computers, processors, .., as well as physical connections between them
* important justifications or motivations for this deployment structure
* quality and/or performance features of this infrastructure
* mapping of software artifacts to elements of this infrastructure

For multiple environments or alternative deployments please copy and adapt this section of arc42 for all relevant environments.
****

[plantuml, "infrastructure-level1", png]
----
node AzureServer{
    node DockerContainer {
        component WebApp
    }
}

node UserDevice {
    node WebBrowser {
        component WebAppImage
    }
}

Actor User


WebApp -d-> WebAppImage : "shows on user device"
WebAppImage <-l- User
----

Motivation::

In the development stage the application will be running on each developer machine using Docker containers. However, in the production stage the application will be running on a Docker environment hosted on Azure, which will be available 24 hours a day. Our goal is to learn how to use docker properly on a server open 24 hours a day.

Quality and/or Performance Features::

We have not tested the application performance so we can't analyze it yet

Mapping of Building Blocks to Infrastructure::

[options="header",cols="1,3"]
|===
| Element | Description
 
| *_WebApp_*
| It is the frontend of our application. It runs the application.
 
| *_Client Device_*
| It is the device of the user. Will show us the execution of the webapp.
|===