ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Deployment View

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

* distribution of a system to multiple locations, environments, computers, processors, .., as well as physical connections between them
* important justifications or motivations for this deployment structure
* quality and/or performance features of this infrastructure
* mapping of software artifacts to elements of this infrastructure

For multiple environments or alternative deployments please copy and adapt this section of arc42 for all relevant environments.
****

[plantuml, "infrastructure-level1", png]
----
node AzureServer{
    node DockerEngine {
      node DockerContainers {
          component Microservices #6c71c4
      }
    }
}

node ExternalServer{
    component WikiData #2aa198
}


node UserDevice {
    node UserAgent {
        component WebApp #d33682
    }
}

Actor User


User -right-> WebApp : "Interacts with"

WebApp -up-> Microservices: "Uses"

WikiData -up-> Microservices : "Provides info"

legend
 |<back:#d33682>   </back>| Client-side |
 |<back:#6c71c4>   </back>| Server-side |
 |<back:#2aa198>   </back>| External source |
endlegend
----

Motivation::

While developing and testing the app it will be run on the developer's localhost enviroment (Using docker for standarization). However, in the production stage we aim for the aplication to be running on a Azure Server. We hope for a high avaiability of the aplication (95% would suffice for our needs).

Quality and/or Performance Features::

We have not tested the application performance so we can't analyze it yet

Mapping of Building Blocks to Infrastructure::

[options="header",cols="1,3"]
|===
| Element | Description
 
| *Azure Server*
| Where the application will be deployed.

| *Docker Engine*
| Daemon inside the azure server which will run our docker containers

| *WebApp*
| It is the frontend of our application. 
 
| *MicroServices*
| They create the backend of the application, they manage every aspect of the application.

| *WikiData*
| It is an external service which will provide the necessary data for the application to work properly.
|===
