ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts

=== Microservices architecture

We have decided that our architecture will be based on microservices, which means that every part of the
aplication will be divided in a service that performs a specific function. The services can communicate witch eachother using their repective APIs or via the shared database


=== User Experience

The application will consist of a website where the user will be able to play our WIQ game, however as we
have not started coding yet we do not have a clear idea of how it will look or if we are adding extra
functionality to the webpage. 

=== Session handling

The application will include a system to control the user access to keep track of their games (And other data), this system will work be based on the token pattern rather than the session pattern. For now we have decided to use JsonWebToken for the token generation and validation

=== Persistence

The persistence between the many microservices of the application will be dealt with using a SQL relational database (Specifically MariaDB) which will help to communicate and sync the different microservices

=== Security & Safety

To ensure customer safety we will store their password using a password safe hash such as bCrypt 

=== Testing

In order to avoid errors in our aplication we will include a bunch of tests that cover both the frontend
and backend areas. (With special attention to e2e tests, unit tests and integration tests)

=== Internationalization

At this point of the proyect we are not sure if we will implement Internationalization, it's a decision that
we will take as the proyect progresses.
