ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Architecture Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****

We have added the ADRs to the Wiki section in the GitHub page, so we provide the links to them:

* https://github.com/Arquisoft/wiq_es1c/wiki/ADR-01-(JavaScript)[ADR 01]
* https://github.com/Arquisoft/wiq_es1c/wiki/ADR-02-(React)[ADR 02]
* https://github.com/Arquisoft/wiq_es1c/wiki/ADR-03-(MariaDB)[ADR 03]
* https://github.com/Arquisoft/wiq_es1c/wiki/ADR-04-(Docker)[ADR 04]
* https://github.com/Arquisoft/wiq_es1c/wiki/ADR-05-(Tailwind-CSS)[ADR 05]
* https://github.com/Arquisoft/wiq_es1c/wiki/ADR-06-(Material-UI)[ADR 06]
* https://github.com/Arquisoft/wiq_es1c/wiki/ADR-07-(Testing-react-library)[ADR 07]
* https://github.com/Arquisoft/wiq_es1c/wiki/ADR-08-(Reacr%E2%80%90router%E2%80%90dom)[ADR 08]
* https://github.com/Arquisoft/wiq_es1c/wiki/ADR-09-%28Sequelize-ORM%29[ADR 09]


