ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Quality Requirements


[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.


.Further Information

See https://docs.arc42.org/section-10/[Quality Requirements] in the arc42 documentation.

****

=== Quality Tree

[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.


****

[options="header",cols="1,2,2,1"]
|===
|Quality Category|Quality|Description|Scenario
| _Usability_ | _Easy to use_ | _Ease of use by the user when playing games or moving around the application._ | _SC1_
| __ | _Easy to learn_ | _Game modes should be intuitive._ | __
| _Maintainability_ | _Robustness_ | _The application must be able to respond to user requests first._ | _SC2_
| __ | _Persistence_ | _There will be no partial loss of user information and data._ | __
| _Performance efficiency_ | _Response time_ | _The application should not exceed 3 seconds of waiting time._ | _SC3_
| _Security_ | _Integrity_ | _User data must be kept confidential and secure at all times._ | __
| _Cultural and Regional_ | _Multi-language_ | _The application texts must be displayed in English._ | _SC4_
|===

=== Quality Scenarios

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****

[options="header",cols="1,4"]
|===
|Id|Scenario
| _SC1_ | _A new user registers in the application and can start playing without the need to view a user guide._
| _SC2_ | _A user performs an action in the application that results in an internal error, but the user can still use the application normally._
| _SC3_ | _A playing user will be viewing the different questions with little or no waiting time._
| _SC4_ | _An English-speaking user will be able to use and play with the application without any problems._
|===