ifndef::imagesdir[:imagesdir: ../images]

[[section-glossary]]
== Glossary

[role="arc42help"]
****
.Contents
The most important domain and technical terms that your stakeholders use when discussing the system.

You can also see the glossary as source for translations if you work in multi-language teams.

.Motivation
You should clearly define your terms, so that all stakeholders

* have an identical understanding of these terms
* do not use synonyms and homonyms


.Form

A table with columns <Term> and <Definition>.

Potentially more columns in case you need translations.


.Further Information

See https://docs.arc42.org/section-12/[Glossary] in the arc42 documentation.

****

[cols="e,2e" options="header"]
|===
|Term |Definition

|Wikidata
|Collaborative platform for storing structured data, supporting multilingual information and facilitating connections between different pieces of knowledge.

|Kanban
|Work methodology focused on limiting work in progress, managing flow and continuosly improving processes.

|Microservices
|Small, independent services that handle specific business functions. Each one operates independently.

|===
