const { DataTypes } = require('sequelize');
const database = require('../database');

const User = require("./user")
const Question = require("./question")

const Game = database.define('Game', {
    id: {
        type: DataTypes.UUID,
        defaultValue: () => uuidv4(), // Autogenerated UUID
        primaryKey: true,
    },
});

User.hasMany(Game)
Game.belongsTo(User)
Game.hasMany(Question)
Question.belongsTo(Game)

module.exports = Question;