const { DataTypes } = require('sequelize');
const database = require('../database');
const { v4: uuidv4 } = require('uuid');

const User = require("./user")
const Question = require("./question")

const Game = database.define('Game', {
    id: {
        type: DataTypes.UUID,
        defaultValue: () => uuidv4(), // Autogenerated UUID
        primaryKey: true,
    }
},{
    timestamps: true,
    defaultScope: {
        order: [['createdAt', 'DESC']], // Order by createdAt in descending order
    },
});

User.hasMany(Game)
Game.belongsTo(User)
Game.hasMany(Question)
Question.belongsTo(Game)

module.exports = Game;