const { DataTypes } = require('sequelize');
const database = require('../database');
const { v4: uuidv4 } = require('uuid');

const Question = require("./question")

const Game = database.define('Game', {
    id: {
        type: DataTypes.UUID,
        defaultValue: () => uuidv4(), // Autogenerated UUID
        primaryKey: true,
    },
    user_id: {
        type: DataTypes.UUID,
    },
    tags: {
        type: DataTypes.STRING,
        defaultValue: ""
    }
},{
    timestamps: true,
    defaultScope: {
        order: [['createdAt', 'DESC']], // Order by createdAt in descending order
    },
});

Game.hasMany(Question)
Question.belongsTo(Game)

module.exports = Game;