const { DataTypes } = require('sequelize');
const database = require('../database');
const { v4: uuidv4 } = require('uuid');

const SettingsGameMode = database.define('SettingsGameMode', {
    id: {
        type: DataTypes.UUID,
        defaultValue: () => uuidv4(), // Autogenerated UUID
        primaryKey: true,
    },
    user_id: {
        type: DataTypes.UUID,
    },
    durationQuestion: {
        type: DataTypes.INTEGER,
        defaultValue: () => 10
    }
});

module.exports = SettingsGameMode;