const { DataTypes } = require('sequelize');
const database = require('../database');
const { v4: uuidv4 } = require('uuid');
const User = require('./user');

const SettingsGameMode = database.define('SettingsGameMode', {
    id: {
        type: DataTypes.UUID,
        defaultValue: () => uuidv4(), // Autogenerated UUID
        primaryKey: true,
    },
    durationQuestion: {
        type: DataTypes.INTEGER,
        defaultValue: () => 10
    }
});

User.hasMany(SettingsGameMode);
SettingsGameMode.belongsTo(User);

module.exports = SettingsGameMode;