'use strict';
const { Model } = require('sequelize');
const { v4: uuidv4 } = require('uuid');

module.exports = (sequelize, DataTypes) => {
  class SettingsGameMode extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  SettingsGameMode.init({
    id: {
      type: DataTypes.UUID,
      defaultValue: () => uuidv4(), // Autogenerated UUID
      primaryKey: true,
    },
    user_id: DataTypes.UUID,
    durationQuestion: {
      type: DataTypes.INTEGER,
      defaultValue: () => 10
    },
    numberOfQuestions: {
      type: DataTypes.INTEGER,
      defaultValue: () => 10
    }
  }, {
    sequelize,
    modelName: 'SettingsGameMode',
  });
  return SettingsGameMode;
};