openapi: 3.0.0
info:
  title: Question Generation Service API
  description: API endpoint for generating questions
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/questions/generate:
    post:
      summary: Generate Question
      description: Generates a new question using a random template.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneratedQuestion'
        '500':
          description: Internal Server Error

  /api/questions/tags:
    post:
      summary: Get All Tags
      description: Retrieves all available tags for question generation.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          description: Internal Server Error

components:
  schemas:
    GeneratedQuestion:
      type: object
      properties:
        title:
          type: string
          description: The generated question title with placeholders replaced.
        answer:
          type: string
          description: The correct answer to the question.
        fake:
          type: array
          items:
            type: string
          description: An array of three different fake answers.
        tags:
          type: array
          items:
            type: string
          description: An array of associated tags for the question.
        lang:
          type: string
          description: The language of the question.
        imageUrl:
          type: string
          description: URL of the image associated with the question (optional).
