openapi: 3.0.0
info:
  title: Game Service API
  description: API endpoints for game management
  version: 1.0.0
servers:
  - url: http://localhost:8003
paths:
  /api/game/new:
    post:
      summary: Start a new game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        '200':
          description: New game started successfully
        '401':
          description: Invalid token
        '500':
          description: Internal server error

  /api/game/next:
    post:
      summary: Get the next question in the game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        '200':
          description: Next question retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: "What is the capital of France?"
                  imageUrl:
                    type: string
                    example: "https://example.com/image.jpg"
                  awnsers:
                    type: array
                    items:
                      type: string
                    example: ["Paris", "London", "Berlin", "Rome"]
        '401':
          description: Invalid token
        '500':
          description: Internal server error

  /api/game/awnser:
    post:
      summary: Submit an answer to the current question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                awnser:
                  type: string
                  example: "Paris"
      responses:
        '200':
          description: Answer submitted successfully
          content:
            application/json:
              schema:
                type: string
                example: "Correct"
        '401':
          description: Invalid token
        '500':
          description: Internal server error

  /api/game/update:
    post:
      summary: Update the current game state
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        '200':
          description: Game state updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: "What is the capital of France?"
                  imageUrl:
                    type: string
                    example: "https://example.com/image.jpg"
                  awnsers:
                    type: array
                    items:
                      type: string
                    example: ["Paris", "London", "Berlin", "Rome"]
                  created:
                    type: string
                    example: "1647865400000"
                  duration:
                    type: string
                    example: "30"
        '401':
          description: Invalid token
        '500':
          description: Internal server error
