openapi: 3.0.0
info:
  title: Friends API
  description: API for friend requests and operations
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/friends/request/send:
    post:
      summary: Send Friend Request
      description: Sends a friend request to another user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: JWT token for authentication.
                to:
                  type: string
                  description: ID of the user to send the request to.
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request

  /api/friends/request/accept:
    post:
      summary: Accept Friend Request
      description: Accepts a friend request from another user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: JWT token for authentication.
                from:
                  type: string
                  description: ID of the user who sent the request.
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request

  /api/friends/request/:
    post:
      summary: Get Friend Requests
      description: Retrieves friend requests received by the authenticated user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: JWT token for authentication.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    from:
                      type: string
                      description: ID of the user who sent the request.
                    to:
                      type: string
                      description: ID of the user who received the request.
        '400':
          description: Bad Request

  /api/friends/:
    post:
      summary: Get Friends
      description: Retrieves the list of friends of the authenticated user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: JWT token for authentication.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    friend1:
                      type: string
                      description: ID of the first friend.
                    friend2:
                      type: string
                      description: ID of the second friend.
        '400':
          description: Bad Request
